"""fixed manufacturer

Revision ID: 45a3c19e7938
Revises: 3ccbe63400af
Create Date: 2018-07-13 09:44:04.010938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45a3c19e7938'
down_revision = '3ccbe63400af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brand', sa.Column('country', sa.String(length=40), nullable=False))
    op.create_unique_constraint(None, 'brand', ['country'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'brand', type_='unique')
    op.drop_column('brand', 'country')
    # ### end Alembic commands ###
