"""Edits the Inventory model to take the user_id and the 

Revision ID: a9318f925dce
Revises: adf95b2c6e29
Create Date: 2018-07-19 15:15:26.399125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9318f925dce'
down_revision = 'adf95b2c6e29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'inventory', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inventory', type_='foreignkey')
    op.drop_column('inventory', 'user_id')
    # ### end Alembic commands ###
